FROM node:20-alpine AS builder

WORKDIR /app

RUN npm install -g pnpm@9

COPY package*.json pnpm-workspace.yaml tsconfig.json ./
COPY packages ./packages
COPY apps/server ./apps/server

RUN pnpm install
RUN pnpm run build:packages
RUN pnpm --filter anonchat-server run build

FROM node:20-alpine AS runner

WORKDIR /app

ENV NODE_ENV=production
ENV PORT=4000

RUN npm install -g pnpm@9

COPY --from=builder /app/package*.json ./
COPY --from=builder /app/pnpm-workspace.yaml ./
COPY --from=builder /app/packages ./packages
COPY --from=builder /app/apps/server/package*.json ./apps/server/
COPY --from=builder /app/apps/server/dist ./apps/server/dist

RUN pnpm install --prod

EXPOSE 4000

CMD ["node", "apps/server/dist/index.js"]
